-- MySQL Script generated by MySQL Workbench
-- Tue Jan 20 20:42:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema karteadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `karteadb` ;

-- -----------------------------------------------------
-- Schema karteadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `karteadb` DEFAULT CHARACTER SET utf8 ;
USE `karteadb` ;

-- -----------------------------------------------------
-- Table `karteadb`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`player` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`player` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `observation` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `karteadb`.`player_kartea_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`player_kartea_session` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`player_kartea_session` (
  `id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `date` DATE NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `phase_reached` INT NULL,
  `level_reached` INT NULL,
  `general_score` INT NULL,
  `q_movement` INT NULL,
  `q_collided_target` INT NULL,
  `q_avoided_target` INT NULL,
  `q_collided_obstacle` INT NULL,
  `q_avoided_obstacle` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_player_session_kartea_player_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_session_kartea_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `karteadb`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `karteadb`.`player_kartea_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`player_kartea_config` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`player_kartea_config` (
  `player_id` INT NOT NULL,
  `player_kartea_session_id` INT NULL,
  `update_session_id` TINYINT NOT NULL,
  `current_phase` INT NOT NULL,
  `current_level` INT NOT NULL,
  `level_time` INT NOT NULL,
  `car_image` VARCHAR(255) NOT NULL,
  `environment_image` VARCHAR(255) NOT NULL,
  `target_image` VARCHAR(255) NOT NULL,
  `obstacle_image` VARCHAR(255) NOT NULL,
  `positive_feedback_image` VARCHAR(255) NOT NULL,
  `neutral_feedback_image` VARCHAR(255) NOT NULL,
  `negative_feedback_image` VARCHAR(255) NOT NULL,
  `positive_feedback_sound` VARCHAR(255) NOT NULL,
  `neutral_feedback_sound` VARCHAR(255) NOT NULL,
  `negative_feedback_sound` VARCHAR(255) NOT NULL,
  `palette` INT NOT NULL,
  `hud` TINYINT NOT NULL,
  `sound` TINYINT NOT NULL,
  PRIMARY KEY (`player_id`),
  INDEX `fk_player_kartea_config_player_kartea_session1_idx` (`player_kartea_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_config_kartea_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `karteadb`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_kartea_config_player_kartea_session1`
    FOREIGN KEY (`player_kartea_session_id`)
    REFERENCES `karteadb`.`player_kartea_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `karteadb`.`player_kartea_session_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`player_kartea_session_detail` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`player_kartea_session_detail` (
  `id` INT NOT NULL,
  `player_kartea_session_id` INT NOT NULL,
  `event_time` TIME NOT NULL,
  `phase` INT NOT NULL,
  `level` INT NOT NULL,
  `player_position` INT NOT NULL,
  `event_position` INT NOT NULL,
  `event_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_player_kartea_session_detail_player_kartea_session1_idx` (`player_kartea_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_kartea_session_detail_player_kartea_session1`
    FOREIGN KEY (`player_kartea_session_id`)
    REFERENCES `karteadb`.`player_kartea_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `karteadb`.`kartea_phase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`kartea_phase` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`kartea_phase` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `karteadb`.`kartea_phase_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `karteadb`.`kartea_phase_level` ;

CREATE TABLE IF NOT EXISTS `karteadb`.`kartea_phase_level` (
  `kartea_phase_id` INT NOT NULL,
  `id` INT NOT NULL,
  `interval` INT NOT NULL,
  `num_obj` INT NOT NULL,
  `obj_type` JSON NOT NULL,
  PRIMARY KEY (`kartea_phase_id`, `id`),
  INDEX `fk_kartea_phase_level_kartea_phase1_idx` (`kartea_phase_id` ASC) VISIBLE,
  CONSTRAINT `fk_kartea_phase_level_kartea_phase1`
    FOREIGN KEY (`kartea_phase_id`)
    REFERENCES `karteadb`.`kartea_phase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
