from typing import TYPE_CHECKING, Optional

from PySide6.QtWidgets import QDialog

from udescjoinvilletteacontroller import InstitutionFacilityEditController
# Local module imports
from udescjoinvilletteaui import Ui_InstitutionFacilityEditView
from udescjoinvilletteawindow import WindowConfig

# class generated by pyside6-uic


# Type checking to avoid circular imports at runtime
if TYPE_CHECKING:
    from udescjoinvilletteamodel import InstitutionFacility


class InstitutionFacilityEditView(
    QDialog, Ui_InstitutionFacilityEditView, WindowConfig
):
    """Modal dialog for creating or editing a institutionfacility record.

    Loads UI from .ui file, applies consistent styling (icons, size, title),
    and delegates all validation and data handling to PlayerEditController.

    Attributes
    ----------
    translator : Optional[QObject]
        Translator object inherited from parent, if available.
    controller : PlayerEditController
        Handles field initialization, validation, and data extraction.
    name_input : QLineEdit
        Input field for the institutionfacility's name.
    birth_date_input : QDateEdit
        Date editor with calendar popup for birth date.
    observation_input : QTextEdit
        Multiline field for additional observations.
    button_box : QDialogButtonBox
        Standard OK/Cancel buttons with custom icons.

    Methods
    -------
    __init__(parent=None, institutionfacility=None)
        Initialize dialog, configure appearance, and create controller.
    """

    def __init__(
        self,
        parent=None,
        institutionfacility: Optional["InstitutionFacility"] = None,
    ):
        """Initialize the institutionfacility creation/editing dialog.

        Sets modality, loads UI, configures dynamic title ("New" or "Edit"),
        applies window sizing relative to parent, sets modern icons on
        buttons, instantiates the controller (which populates fields when
        editing), and connects button box signals to controller methods.

        Parameters
        ----------
        parent : Optional[QWidget], optional
            Parent widget (usually PlayerListView or main window). Used for
            translator, icon, and title inheritance.
        institutionfacility : Optional[InstitutionFacility], optional
            institutionfacility instance to edit.
            If None, dialog is in creation mode.
        """
        super().__init__(parent)

        # Load the interface generated by Qt Designer
        self.setupUi(self)

        # ------------------------------------------------------------------
        # Window configuration (title, icon, relative sizing)
        # ------------------------------------------------------------------
        action = (
            self.tr("Novo") if not institutionfacility else self.tr("Editar")
        )

        # title = parent.parent().windowTitle()
        self.setup_window(
            f"{self.windowTitle()} - {action}",
            self.windowIcon(),
            WindowConfig.DECREMENT_SIZE_PERCENT,
            10,  # percent decrease in width
            10,  # percent decrease in height
            parent,
        )

        # ------------------------------------------------------------------
        # Instantiate the controller
        # (automatically populates fields if editing)
        # ------------------------------------------------------------------
        self.controller = InstitutionFacilityEditController(
            self, institutionfacility
        )
