from typing import TYPE_CHECKING, Optional

import qtawesome as qta
from PySide6.QtWidgets import QDialog, QDialogButtonBox

# Local module imports
from udescjoinvilletteaui import \
    Ui_PlayerEditView  # class generated by pyside6-uic
from udescjoinvilletteawindow import WindowConfig

# Type checking to avoid circular imports at runtime
if TYPE_CHECKING:
    from udescjoinvilletteamodel import Player


class PlayerEditView(QDialog, Ui_PlayerEditView, WindowConfig):
    """Modal dialog for creating or editing a player record.

    Loads UI from .ui file, applies consistent styling (icons, size, title),
    and delegates all validation and data handling to PlayerEditController.

    Attributes
    ----------
    translator : Optional[QObject]
        Translator object inherited from parent, if available.
    controller : PlayerEditController
        Handles field initialization, validation, and data extraction.
    name_input : QLineEdit
        Input field for the player's name.
    birth_date_input : QDateEdit
        Date editor with calendar popup for birth date.
    observation_input : QTextEdit
        Multiline field for additional observations.
    button_box : QDialogButtonBox
        Standard OK/Cancel buttons with custom icons.

    Methods
    -------
    __init__(parent=None, player=None)
        Initialize dialog, configure appearance, and create controller.
    """

    def __init__(self, parent=None, player: Optional["Player"] = None):
        """Initialize the player creation/editing dialog.

        Sets modality, loads UI, configures dynamic title ("New" or "Edit"),
        applies window sizing relative to parent, sets modern icons on
        buttons, instantiates the controller (which populates fields when
        editing), and connects button box signals to controller methods.

        Parameters
        ----------
        parent : Optional[QWidget], optional
            Parent widget (usually PlayerListView or main window). Used for
            translator, icon, and title inheritance.
        player : Optional[Player], optional
            Player instance to edit. If None, dialog is in creation mode.
        """
        from udescjoinvilletteacontroller import PlayerEditController

        super().__init__(parent)
        self.setModal(True)

        # Inherit translator from parent, if present
        self.translator = (
            parent.translator if hasattr(parent, "translator") else None
        )

        # Load the interface generated by Qt Designer
        self.setupUi(self)

        # ------------------------------------------------------------------
        # Window configuration (title, icon, relative sizing)
        # ------------------------------------------------------------------
        action = "Jogador - Editar" if player else "Jogador - Novo"
        title = parent.parent().get_title()
        self.setup_window(
            f"{title} - {action}",
            parent.windowIcon() if parent else None,
            WindowConfig.DECREMENT_SIZE_PERCENT,
            40,  # percent decrease in width
            40,  # percent decrease in height
            parent,
        )

        # ------------------------------------------------------------------
        # Custom icons on OK and Cancel buttons (consistent with project style)
        # ------------------------------------------------------------------
        ok_button = self.button_box.button(QDialogButtonBox.Ok)
        ok_button.setIcon(qta.icon("fa6s.check", color="green"))
        ok_button.setText(self.tr("OK"))
        ok_button.setToolTip(self.tr("Gravar operação corrente"))

        cancel_button = self.button_box.button(QDialogButtonBox.Cancel)
        cancel_button.setIcon(qta.icon("fa6s.xmark", color="red"))
        cancel_button.setText(self.tr("Cancelar"))
        cancel_button.setToolTip(self.tr("Cancelar operação corrente"))

        # ------------------------------------------------------------------
        # Instantiate the controller
        # (automatically populates fields if editing)
        # ------------------------------------------------------------------
        self.controller = PlayerEditController(self, player)

        # Remove all automatic connections from button_box
        # This prevents default accept/reject behavior QT signals
        # from interfering with our custom controller methods
        self.button_box.accepted.disconnect()
        self.button_box.rejected.disconnect()

        # ------------------------------------------------------------------
        # Connect buttons to controller (validation + accept/reject handling)
        # ------------------------------------------------------------------
        self.button_box.accepted.connect(self.controller.handle_ok)
        self.button_box.rejected.connect(self.controller.handle_cancel)
