from typing import TYPE_CHECKING, Callable, Optional

import qtawesome as qta
from PySide6.QtGui import QCloseEvent
from PySide6.QtWidgets import QDialog, QHeaderView, QMessageBox

# Local module import
from udescjoinvilletteacontroller import PlayerListController
from udescjoinvilletteaui import Ui_PlayerListView
from udescjoinvilletteawindow import WindowConfig

# Type checking to prevent circular import on run time
if TYPE_CHECKING:
    from udescjoinvilletteamodel import Player
    from udescjoinvilletteaview import PlayerEditView


class PlayerListView(QDialog, Ui_PlayerListView, WindowConfig):
    """A dialog for displaying and managing a list of players.

    This class inherits from QDialog, Ui_PlayerListView, and WindowConfig
    to provide a UI for listing players, with functionality for adding,
    editing, deleting, and searching players. It uses a controller to
    handle data operations and integrates with a UI generated by pyside6-uic.

    Attributes
    ----------
    translator : Optional[object]
        Translator object from parent, if available.
    controller : PlayerListController
        Controller for handling player data operations.
    table : QTableWidget
        Widget that displays the list of players.
    new_button : QPushButton
        Button to trigger the creation of a new player.
    edit_button : QPushButton
        Button to trigger the editing of the selected player.
    delete_button : QPushButton
        Button to trigger the deletion of the selected player.
    search_input : QLineEdit
        Input field used to filter the players shown in the table.

    Methods
    -------
    __init__(parent=None, player_edit_view_factory=None)
        Initialize the PlayerListView dialog.
    on_new_button_clicked()
        Handle the 'New' button click event.
    on_edit_button_clicked()
        Handle the 'Edit' button click event.
    on_delete_button_clicked()
        Handle the 'Delete' button click event.
    on_search_input_textChanged(text)
        Handle text changes in the search input field.
    on_table_selection_changed()
        Handle changes in table selection.
    closeEvent(event)
        Handle the dialog close event.
    """

    def __init__(
        self,
        parent: Optional[QDialog] = None,
        player_edit_view_factory: Optional[
            Callable[[Optional[QDialog], Optional["Player"]], "PlayerEditView"]
        ] = None,
    ) -> None:
        """Initialize the PlayerListView dialog.

        Sets up the UI using the generated Ui_PlayerListView, configures
        window properties, initializes the controller, and connects signals
        to slots for user interactions. Loads initial player data.

        Parameters
        ----------
        parent : Optional[QDialog], optional
            The parent dialog. Defaults to None.
        player_edit_view_factory : Optional[Callable[[Optional[QDialog],
            Optional[Player]], PlayerEditView]], optional Factory function
            to create a PlayerEditView instance. Defaults to None.

        Returns
        -------
        None
        """

        super().__init__(parent)
        self.setModal(True)
        self.translator = (
            parent.translator if hasattr(parent, "translator") else None
        )

        # Setup UI interface Ui_PlayerListView
        self.setupUi(self)

        # Set up window properties
        self.setup_window(
            parent.title + " - Jogador",
            parent.windowIcon() if parent else None,
            WindowConfig.DECREMENT_SIZE_PERCENT,
            10,
            5,
            parent,
        )

        # Initialize controller
        self.controller = PlayerListController(self, player_edit_view_factory)

        # Set up table properties not fully handled by .ui file
        self.table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeToContents
        )

        # Set up button icons
        self.new_button.setIcon(qta.icon("fa6s.plus", color="blue"))
        self.edit_button.setIcon(qta.icon("fa6s.pen-to-square", color="black"))
        self.delete_button.setIcon(qta.icon("fa6s.trash", color="red"))

        # Events signals and slots
        self.new_button.clicked.connect(self.on_new_button_clicked)
        self.edit_button.clicked.connect(self.on_edit_button_clicked)
        self.delete_button.clicked.connect(self.on_delete_button_clicked)
        self.search_input.textChanged.connect(self.on_search_input_textChanged)
        self.table.selectionModel().selectionChanged.connect(
            self.on_table_selection_changed
        )

        # Load initial data
        self.controller.load_players()

    def on_new_button_clicked(self):
        """Handle the 'New' button click event.

        Triggers the controller to initiate the creation of a new player,
        typically opening a dialog for entering new player details.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """
        self.controller.handle_new_player()

    def on_edit_button_clicked(self):
        """Handle the 'Edit' button click event.

        Triggers the controller to edit the currently selected player,
        typically opening a dialog pre-filled with the player's data.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """
        self.controller.handle_edit_player()

    def on_delete_button_clicked(self):
        """Handle the 'Delete' button click event.

        Triggers the controller to delete the currently selected player,
        typically after a confirmation prompt.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """
        self.controller.delete_player()

    def on_search_input_textChanged(self, text: str):
        """Handle text changes in the search input field.

        Filters the player list based on the input text by calling the
        controller's filter method, updating the table display.

        Parameters
        ----------
        text : str
            The text entered in the search input field.

        Returns
        -------
        None
        """
        self.controller.filter_players(text)

    def on_table_selection_changed(self):
        """Handle changes in table selection.

        Notifies the controller when the table selection changes, enabling
        or disabling actions like edit and delete based on selection.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """
        self.controller.on_table_selection()

    def closeEvent(self, event: QCloseEvent) -> None:
        """Handle the dialog close event.

        Displays a confirmation dialog asking if the user wants to exit.
        If confirmed, accepts the close event; otherwise, ignores it.

        Parameters
        ----------
        event : QCloseEvent
            The close event triggered by the dialog.

        Returns
        -------
        None
        """
        msg_box = QMessageBox()
        msg_box.setWindowIcon(
            self.parent().windowIcon() if self.parent() else self.windowIcon()
        )
        msg_box.setIcon(QMessageBox.Question)
        msg_box.setWindowTitle(
            self.parent().windowTitle()
            if self.parent()
            else self.windowTitle()
        )
        msg_box.setText(self.tr("Deseja sair do cadastro?"))
        msg_box.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        msg_box.button(QMessageBox.Yes).setText(self.tr("Sim"))
        msg_box.button(QMessageBox.No).setText(self.tr("Não"))
        if msg_box.exec() == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()
