from typing import TYPE_CHECKING, Optional

from PySide6.QtWidgets import QDialog

# Local module imports
from udescjoinvilletteaui import \
    Ui_PlayerEditView  # class generated by pyside6-uic
from udescjoinvilletteawindow import WindowConfig

# Type checking to avoid circular imports at runtime
if TYPE_CHECKING:
    from udescjoinvilletteamodel import Player


class PlayerEditView(QDialog, Ui_PlayerEditView, WindowConfig):
    """Modal dialog for creating or editing a player record.

    Loads UI from .ui file, applies consistent styling (icons, size, title),
    and delegates all validation and data handling to PlayerEditController.

    Attributes
    ----------
    translator : Optional[QObject]
        Translator object inherited from parent, if available.
    controller : PlayerEditController
        Handles field initialization, validation, and data extraction.
    name_input : QLineEdit
        Input field for the player's name.
    birth_date_input : QDateEdit
        Date editor with calendar popup for birth date.
    observation_input : QTextEdit
        Multiline field for additional observations.
    button_box : QDialogButtonBox
        Standard OK/Cancel buttons with custom icons.

    Methods
    -------
    __init__(parent=None, player=None)
        Initialize dialog, configure appearance, and create controller.
    """

    def __init__(self, parent=None, player: Optional["Player"] = None):
        """Initialize the player creation/editing dialog.

        Sets modality, loads UI, configures dynamic title ("New" or "Edit"),
        applies window sizing relative to parent, sets modern icons on
        buttons, instantiates the controller (which populates fields when
        editing), and connects button box signals to controller methods.

        Parameters
        ----------
        parent : Optional[QWidget], optional
            Parent widget (usually PlayerListView or main window). Used for
            translator, icon, and title inheritance.
        player : Optional[Player], optional
            Player instance to edit. If None, dialog is in creation mode.
        """
        from udescjoinvilletteacontroller import PlayerEditController

        super().__init__(parent)

        # Load the interface generated by Qt Designer
        self.setupUi(self)

        # ------------------------------------------------------------------
        # Window configuration (title, icon, relative sizing)
        # ------------------------------------------------------------------
        action = self.tr("Novo")

        if player:
            action = self.tr("Editar")

        # title = parent.parent().windowTitle()
        self.setup_window(
            f"{self.windowTitle()} - {action}",
            self.windowIcon(),
            WindowConfig.DECREMENT_SIZE_PERCENT,
            40,  # percent decrease in width
            40,  # percent decrease in height
            parent,
        )

        # ------------------------------------------------------------------
        # Instantiate the controller
        # (automatically populates fields if editing)
        # ------------------------------------------------------------------
        self.controller = PlayerEditController(self, player)

        # ------------------------------------------------------------------
        # Connect buttons to controller (validation + accept/reject handling)
        # ------------------------------------------------------------------
        self.pb_ok.clicked.connect(self.controller.handle_ok)
        self.pb_cancel.clicked.connect(self.controller.handle_cancel)
