from typing import TYPE_CHECKING, Optional

from PySide6.QtWidgets import QDialog

# Local module imports
from udescjoinvilletteacontroller import ProfessionalEditController
# class generated by pyside6-uic
from udescjoinvilletteaui import Ui_ProfessionalEditView
from udescjoinvilletteawindow import WindowConfig

# Type checking to avoid circular imports at runtime
if TYPE_CHECKING:
    from udescjoinvilletteamodel import Professional


class ProfessionalEditView(
    QDialog, Ui_ProfessionalEditView, WindowConfig
):
    """Modal dialog for creating or editing a professional record.

    Loads UI from .ui file, applies consistent styling (icons, size, title),
    and delegates all validation and data handling to PlayerEditController.

    Attributes
    ----------
    translator : Optional[QObject]
        Translator object inherited from parent, if available.
    controller : PlayerEditController
        Handles field initialization, validation, and data extraction.
    name_input : QLineEdit
        Input field for the professional's name.
    birth_date_input : QDateEdit
        Date editor with calendar popup for birth date.
    observation_input : QTextEdit
        Multiline field for additional observations.
    button_box : QDialogButtonBox
        Standard OK/Cancel buttons with custom icons.

    Methods
    -------
    __init__(parent=None, professional=None)
        Initialize dialog, configure appearance, and create controller.
    """

    def __init__(
        self,
        parent=None,
        professional: Optional["Professional"] = None,
    ):
        """Initialize the professional creation/editing dialog.

        Sets modality, loads UI, configures dynamic title ("New" or "Edit"),
        applies window sizing relative to parent, sets modern icons on
        buttons, instantiates the controller (which populates fields when
        editing), and connects button box signals to controller methods.

        Parameters
        ----------
        parent : Optional[QWidget], optional
            Parent widget (usually PlayerListView or main window). Used for
            translator, icon, and title inheritance.
        professional : Optional[Professional], optional
            professional instance to edit.
            If None, dialog is in creation mode.
        """

        super().__init__(parent)

        # Load the interface generated by Qt Designer
        self.setupUi(self)

        # ------------------------------------------------------------------
        # Window configuration (title, icon, relative sizing)
        # ------------------------------------------------------------------
        action = (
            self.tr("Novo") if not professional else self.tr("Editar")
        )

        self.setup_window(
            f"{self.windowTitle()} - {action}",
            self.windowIcon(),
            WindowConfig.DECREMENT_SIZE_PERCENT,
            10,  # percent decrease in width
            10,  # percent decrease in height
            parent,
        )

        # ------------------------------------------------------------------
        # Instantiate the controller
        # (automatically populates fields if editing)
        # ------------------------------------------------------------------
        self.controller = ProfessionalEditController(
            self, professional
        )
