"""
udescjoinvilletteaui

A Python package for UI interface.

This package provides UI classes generated by pyside6-uic.

Attributes
----------
__version__ : str
    The current version of the package.
__date__ : str
    The release date of this version.
__author__ : str
    The development team.
__license__ : str
    The license under which the package is distributed.

See Also
--------
PlayerListView
    Lists player data in a structured format.

Notes
-----
This package is maintained by the Larva UDESC team and is under active
development. Contributions and bug reports are welcome at:
https://github.com/larva-udesc/udesc_ttea_view
"""

# Define the __all__ variable
__all__ = [
    "Ui_AboutView",
    "Ui_CalibrationView",
    "Ui_LanguageView",
    "Ui_MainView",
    "Ui_PlayerEditView",
    "Ui_PlayerListView",
]

__version__ = "1.0.0"
__date__ = "2025-12-25"
__author__ = "Larva UDESC"
__license__ = "MIT License"

# Import the submodules
from .aboutviewui import Ui_AboutView
from .calibrationui import Ui_CalibrationView
from .languageviewui import Ui_LanguageView
from .mainviewui import Ui_MainView
from .playereditviewui import Ui_PlayerEditView
from .playerlistviewui import Ui_PlayerListView
